apiVersion: v2
name: coredns
version: 1.39.2
appVersion: 1.12.0
home: https://coredns.io
icon: https://coredns.io/images/CoreDNS_Colour_Horizontal.png
description: CoreDNS is a DNS server that chains plugins and provides Kubernetes DNS Services
keywords:
  - coredns
  - dns
  - kubedns
sources:
  - https://github.com/coredns/coredns
maintainers:
  - name: mrueg
  - name: haad
  - name: hagaibarel
  - name: shubham-cmyk
type: application
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: improve default readiness probe config for shutdown
