name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.1

      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Add Helm repo
        run: |
          helm repo add cpa https://kubernetes-sigs.github.io/cluster-proportional-autoscaler
          helm repo update

      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Run Helm unit tests
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          mkdir -p test-results
          for chart in $(ct list-changed --target-branch ${{ github.event.repository.default_branch }}); do
            echo "Running unit tests for $chart"
            helm unittest --strict --output-type JUnit \
              --output-file test-results/$(basename $chart)-helm-unittest.xml $chart
          done
      - name: Upload Helm unittest report
        if: steps.list-changed.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: helm-unittest-reports
          path: test-results/

      - name: Publish JUnit test results
        if: steps.list-changed.outputs.changed == 'true'
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: test-results/*.xml
          check_name: Helm Unittest Report
          fail_on_failure: true
          require_tests: true
          require_passed_tests: true
          include_passed: true
          detailed_summary: true
          job_summary: true

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
        if: steps.list-changed.outputs.changed == 'true'
